site_name: Documentación de GOP
theme:
  name: material
  language: es
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: assets/isotipo_8@4x.png
  favicon: assets/isotipo_8@4x.png

  features:
  - navigation.sections 
  - search.highlight
  - search.suggest
  - navigation.footer
  
  plugins:
  - optimize
  - search



extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Squad ALPHA &copy; 2024 | Grupo de Simulación Táctica en ARMA 3.